### ISSUE TITLE
报错了！！！是配置有问题么？

### ISSUE THREAD

**Issue by frinder6** [lefreet/vue-form#2]
ERROR in ./node_modules/@lefreet/vue-form/src/components/field-tree.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> 
| <template>
|   <div class="field-tree">
 @ ./node_modules/@lefreet/vue-form/index.js 11:0-49 15:0-25:1
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 webpack/hot/dev-server ./src/main.js

ERROR in ./node_modules/@lefreet/vue-form/src/components/field-checkbox.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <template>
|   <base-checkbox :options="options" v-model="val"></base-checkbox>
| </template>
 @ ./node_modules/@lefreet/vue-form/index.js 5:0-57 15:0-25:1
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 webpack/hot/dev-server ./src/main.js

ERROR in ./node_modules/@lefreet/vue-form/src/components/field-date.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <template>
|   <base-date :options="options" v-model="val"></base-date>
| </template>
 @ ./node_modules/@lefreet/vue-form/index.js 10:0-49 15:0-25:1
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 webpack/hot/dev-server ./src/main.js

**Comment by frinder6** [comment]
"dependencies": {
    "@lefreet/vue-form": "^1.0.8",
    "axios": "^0.18.0",
    "element-ui": "^2.4.3",
    "vue": "^2.5.16",
    "vue-axios": "^2.1.2",
    "vue-router": "^3.0.1"
  }

**Comment by lefreet** [comment]
是否配置了beble环境？

**Comment by frinder6** [comment]
有配置的，如下：
{
  "presets": [
    "es2015",
    [
      "env",
      {
        "modules": false
      }
    ],
    "stage-2"
  ],
  "plugins": [
    [
      "transform-runtime",
      "component",
      [
        {
          "libraryName": "element-ui",
          "styleLibraryName": "theme-chalk"
        }
      ]
    ]
  ]
}
安装后报文件格式不对，不知道怎么回事哟

**Comment by lefreet** [comment]
@frinder6  需要检查下脚手架的配置，是否node_modules下的vue文件有被loader命中解析
