### ISSUE TITLE
field-tree

### ISSUE THREAD

**Issue by Thyiad** [lefreet/vue-form#4]
Hi，起因是发现一个兼容性bug，field-tree在edge里面，弹出来的tree很窄，然后看了一下代码。。
field-tree的mounted里面的代码有问题呀！~

` // 保持弹框宽度和输入框一致
    let $input = this.$refs['input'].$el
    let observer = new MutationObserver((mutations, observer) => {
      this.popWidth = $input.getBoundingClientRect().width - 24
      observer.disconnect()
    })
    observer.observe($input, {
      attributes: true,
      subtree: false,
      characterData: false,
      childList: false
    })
    this.setShowValue()
    this.getData()`

这段代码按注释来看，应该是想监听input的width，然后动态改变tree的width，因为没有这种监听事件，所以用了MutationObserver来监听attribute改变，而且还只是一次性的（很奇怪），但这个是有问题的。。
因为input的width是设置为100%的，按理来说是不会触发observer的，我实际跟踪下来，发现在chrome里面会触发（虽然触发，但是没有任何新旧修改数据），edge里面不会触发。
总之，很奇怪，反正是达不到监听input的宽度动态改变tree宽度的，感觉如果要监听，只能监听window的resize事件了
但这个没有必要，至少目前对于我来说是的，所以我直接设置popWidth了：
`
    let $input = this.$refs['input'].$el
    this.popWidth = $input.getBoundingClientRect().width - 24
    this.setShowValue()
    this.getData()
`

**Comment by lefreet** [comment]
为了处理tabs中渲染时，容器display:none，导致input在mounted后widh为0的问题才做的处理，看样子有兼容问题。改为focus触发了，可以更新看看。

**Comment by Thyiad** [comment]
你改日期那个有问题吧，日期区间还是会报错的。我之前提了pr就是说这个区间问题的
